require 'hoe'
require './lib/$filename$/version.rb'

Hoe.spec '$name$' do

  self.version = $module$::VERSION

  self.summary = '$name$ - TODO: add summary'
  self.description = summary

  self.urls    = ['TODO: add url']

  self.author  = 'TODO: add author'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.extra_deps = [
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 1.9.2'
  }

end
